package com.rvvcode.ai.mcp.server.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Service
public class ProjectGenerator {

    private static final Logger log = LoggerFactory.getLogger(ProjectGenerator.class);

    @Tool(name = "bootstrap_project", description = "Generate a production-ready Spring Boot 3 skeleton with Oracle JPA, MapStruct and OpenAPI")
    public String bootstrapProject(
            @ToolParam(description = "Project name / root folder") String projectName,
            @ToolParam(description = "Base Java package, for example com.acme.platform") String basePackage,
            @ToolParam(description = "Functional API requirements in plain text") String apiRequirements) {

        log.info("Entering bootstrapProject for projectName={}", projectName);
        try {
            Path projectRoot = Paths.get(projectName).toAbsolutePath();
            if (Files.exists(projectRoot)) {
                return "Project already exists at " + projectRoot;
            }

            createDirectory(projectRoot.resolve("src/main/java").resolve(basePackage.replace('.', '/')));
            createDirectory(projectRoot.resolve("src/main/resources"));
            createDirectory(projectRoot.resolve("src/test/java").resolve(basePackage.replace('.', '/')));

            writeFile(projectRoot.resolve("pom.xml"), pomXml(projectName));
            writeFile(projectRoot.resolve("src/main/resources/application.yml"), applicationYml());
            writeFile(projectRoot.resolve("README.md"), readme(projectName, basePackage, apiRequirements));

            Path featureRoot = projectRoot.resolve("src/main/java").resolve(basePackage.replace('.', '/')).resolve("customer");
            createDirectory(featureRoot);
            writeFile(featureRoot.resolve("CustomerController.java"), controllerSkeleton(basePackage));
            writeFile(featureRoot.resolve("CustomerService.java"), serviceSkeleton(basePackage));
            writeFile(featureRoot.resolve("CustomerRepository.java"), repositorySkeleton(basePackage));

            return "Bootstrapped enterprise project at " + projectRoot;
        } catch (IOException ex) {
            log.error("Failed to bootstrap project", ex);
            return "Failed to bootstrap project: " + ex.getMessage();
        } finally {
            log.info("Exiting bootstrapProject for projectName={}", projectName);
        }
    }

    private void createDirectory(Path path) throws IOException {
        Files.createDirectories(path);
    }

    private void writeFile(Path path, String content) throws IOException {
        createDirectory(path.getParent());
        Files.writeString(path, content);
    }

    private String pomXml(String projectName) {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <parent>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-parent</artifactId>
                        <version>3.3.5</version>
                        <relativePath/>
                    </parent>
                    <groupId>com.generated</groupId>
                    <artifactId>%s</artifactId>
                    <version>0.0.1-SNAPSHOT</version>
                    <name>%s</name>
                    <description>Generated by MCP enterprise stack automation server</description>

                    <properties>
                        <java.version>17</java.version>
                        <mapstruct.version>1.5.5.Final</mapstruct.version>
                    </properties>

                    <dependencies>
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-web</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-data-jpa</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.springdoc</groupId>
                            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                            <version>2.6.0</version>
                        </dependency>
                        <dependency>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct</artifactId>
                            <version>${mapstruct.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.oracle.database.jdbc</groupId>
                            <artifactId>ojdbc11</artifactId>
                            <scope>runtime</scope>
                        </dependency>
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-test</artifactId>
                            <scope>test</scope>
                        </dependency>
                    </dependencies>

                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <configuration>
                                    <source>${java.version}</source>
                                    <target>${java.version}</target>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>org.mapstruct</groupId>
                                            <artifactId>mapstruct-processor</artifactId>
                                            <version>${mapstruct.version}</version>
                                        </path>
                                    </annotationProcessorPaths>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """.formatted(projectName, projectName);
    }

    private String applicationYml() {
        return """
                spring:
                  datasource:
                    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
                    username: app_user
                    password: app_password
                    driver-class-name: oracle.jdbc.OracleDriver
                  jpa:
                    hibernate:
                      ddl-auto: validate
                    properties:
                      hibernate:
                        dialect: org.hibernate.dialect.OracleDialect
                  jackson:
                    default-property-inclusion: non_null
                springdoc:
                  swagger-ui:
                    path: /swagger-ui.html
                """;
    }

    private String readme(String projectName, String basePackage, String apiRequirements) {
        return """
                # %s

                Generated with MCP bootstrap_project tool.

                - Base package: `%s`
                - Architecture: Package-by-Feature
                - Stack: Spring Boot 3, Oracle JPA, MapStruct, SpringDoc OpenAPI

                ## API requirements
                %s
                """.formatted(projectName, basePackage, apiRequirements == null ? "N/A" : apiRequirements);
    }

    private String controllerSkeleton(String basePackage) {
        return """
                package %s.customer;

                import org.springframework.web.bind.annotation.GetMapping;
                import org.springframework.web.bind.annotation.RequestMapping;
                import org.springframework.web.bind.annotation.RestController;

                import java.util.List;

                @RestController
                @RequestMapping("/api/customers")
                public class CustomerController {

                    private final CustomerService service;

                    public CustomerController(CustomerService service) {
                        this.service = service;
                    }

                    @GetMapping
                    public List<String> findAll() {
                        return service.findAll();
                    }
                }
                """.formatted(basePackage);
    }

    private String serviceSkeleton(String basePackage) {
        return """
                package %s.customer;

                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.springframework.stereotype.Service;
                import org.springframework.transaction.annotation.Transactional;

                import java.util.List;

                @Service
                @Transactional(readOnly = true)
                public class CustomerService {

                    private static final Logger log = LoggerFactory.getLogger(CustomerService.class);
                    private final CustomerRepository repository;

                    public CustomerService(CustomerRepository repository) {
                        this.repository = repository;
                    }

                    public List<String> findAll() {
                        log.info("Entering CustomerService.findAll");
                        List<String> result = repository.findAllCustomerNames();
                        log.info("Exiting CustomerService.findAll size={}", result.size());
                        return result;
                    }
                }
                """.formatted(basePackage);
    }

    private String repositorySkeleton(String basePackage) {
        return """
                package %s.customer;

                import org.springframework.data.jpa.repository.JpaRepository;
                import org.springframework.data.jpa.repository.Query;

                import java.util.List;

                public interface CustomerRepository extends JpaRepository<CustomerEntity, Long> {

                    @Query("select c.name from CustomerEntity c")
                    List<String> findAllCustomerNames();
                }
                """.formatted(basePackage);
    }
}
